### ISSUE TITLE
[FeatureRequest] Add TechAge Apiary

### ISSUE THREAD

**Issue by Lesya-cpp** [Archtec-io/bugtracker#107]
This is request to add the [ta_apiary](https://content.minetest.net/packages/Olesya_95/ta_apiary) mod to the server. The mod adds industrial (TechAge) way to automate beekeeping in mods [Bees](https://content.minetest.net/packages/TenPlus1/bees) and [Mobs animal](https://content.minetest.net/packages/TenPlus1/mobs_animal).

The Bees mod adds Industrial Bee Hive with pipeworks support but no tubes support. The TA Apiary mod adds TA Apiary - a beehive with tubes support. There is also a new machine TA Honey Extractor with TA2, TA3 and TA4 versions for extracting honey and wax from filled frames.

Beehives from the Mobs animal mod don't have any pipes / tubes support. The TA Apiary mod adds TA Honey Sink - a new TechAge machine (TA2, TA3 and TA4 versions) to sink honey from the Mobs animal beehives. Just place your beehive on top of Honey Sink and provide the machine with some energy.

**Comment by Niklp09** [comment]
Added in https://github.com/Archtec-io/archtec-mods/commit/9311a9c21ad86152b8a99f587bea37ee14744447
Fixed some issues in https://gitlab.com/lesya_minetest_mods/ta_apiary/-/commit/4f83b32e4a38a54e282920544ca3246317541049
