### ISSUE TITLE
Additional news popup disruption

### ISSUE THREAD

**Issue by vintprox** [Archtec-io/bugtracker#120]
There is a usual MOTD that appears upon join, and then there is another one. Another popup appears after a minute of playing. This thing disrupts anything I was doing before and provides no value.

Yesterday, I was typing a long message in chat and this thing popped up. I have to type again...

It pops up on top of inventory, too. Takes me out of the experience easily. Now imagine if I was doing something else like dragging diamonds and other goodies, what would happen.

This auxiliary news popup needs to go away.

**Comment by Niklp09** [comment]
>This auxiliary news popup needs to go away.

It will go away in a few weeks. :-)

The first formspec (you called it MOTD) is the news formspec, it's always there. The second formspec appears after two minutes and wars you about the upcomming server address change. I'll remove it when the address is changed. (scheduled for 2023-10-1).

**Comment by Niklp09** [comment]
Address changed, formspec will be disabled in the next hours.
