### ISSUE TITLE
Show players list by a press of key

### ISSUE THREAD

**Issue by vintprox** [Archtec-io/bugtracker#124]
There is a nice feature that I think could be a nominee for default Minetest game, but unfortunately is not. You can see it in many multiplayer games and it usually involves holding a `Tab` key to show players list. Recently, I came across A.E.S., they've done it so when you hold `Aux1` (`E`) key, you see the players list popping up. This is awfully convenient when you don't want to memorize and type the command all the time, plus it adds UI/UX clarity to the most primary feature in MMOs.

There is one implementation I know of: https://gitlab.com/zughy-friends-minetest/hub/-/tree/master/playerlist

**Comment by Niklp09** [comment]
Added in https://github.com/Archtec-io/archtec/commit/22bfd2beb5ee5f7f4d978493ec1410bf1e16bca6

![image](https://github.com/Archtec-io/bugtracker/assets/89982526/28299d8a-ead5-4d0b-b51e-539140aaafde)
