### ISSUE TITLE
Minetest crashes when joining the server (Windows)

### ISSUE THREAD

**Issue by Niklp09** [Archtec-io/bugtracker#19]
Reported by IanWelt:
kann archtec nicht mehr joinen, client stürzt andauernd ab sowie es versuche. Andere geht nach wie vor (WuWe).

![minetest](https://user-images.githubusercontent.com/89982526/195434517-b2cd7d00-6ac5-47d1-a683-40aa958d22d5.PNG)

**Comment by debagos** [comment]
Client Version?
Wie schaut es mit anderen Versionen aus, bleibt das Problem bestehen?

**Comment by Niklp09** [comment]
Hat sich von selbst gelöst

**Comment by Niklp09** [comment]
Nicht reproduzierbar, wird geschlossen
